### ISSUE TITLE
Build Failing

### ISSUE THREAD

**Issue by AlexR1712** [fox-one/mornin.fm#1]
When running npm run build getting this error:

```
Hash: f2294c19bc8aa82c1e7b
Version: webpack 4.43.0
Time: 162782ms
Built at: 05/04/2020 4:45:00 PM
                         Asset       Size  Chunks                                Chunk Names
../server/client.manifest.json   17.8 KiB          [emitted]
       468193a8573da46e2589.js   11.2 KiB       3  [emitted] [immutable]         commons.pages/_name/index
       65f37ecacbf705979043.js    483 KiB       7  [emitted] [immutable]  [big]  vendors.app
       77fe22fa5334200e6942.js   24.3 KiB       4  [emitted] [immutable]         pages/_name/index
       803a26be9e0f0a8280b6.js   73.5 KiB       0  [emitted] [immutable]         vendors.pages/_name/index.pages/index
       9fa2569ee8c2f5f0d5b6.js    190 KiB       2  [emitted] [immutable]         commons.app
                      LICENSES  923 bytes          [emitted]
       b298033b7aae9020e397.js   14.6 KiB       5  [emitted] [immutable]         pages/index
       c02bcc4f7733e07b91a0.js   98.3 KiB       1  [emitted] [immutable]         app
       ccb9620fe7366fe7e508.js    4.3 KiB       8  [emitted] [immutable]
       fbb11d08e8b5aae3613d.js    2.4 KiB       6  [emitted] [immutable]         runtime
        manifest.e1fa8fe2.json  233 bytes          [emitted]
 + 1 hidden asset
Entrypoint app = fbb11d08e8b5aae3613d.js 9fa2569ee8c2f5f0d5b6.js 65f37ecacbf705979043.js c02bcc4f7733e07b91a0.js

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets:
  65f37ecacbf705979043.js (483 KiB)

ERROR in /Users/alexanderrodriguez/Documents/git-repos/mornin.fm/node_modules/@nuxt/types/config/build.d.ts
ERROR in /Users/alexanderrodriguez/Documents/git-repos/mornin.fm/node_modules/@nuxt/types/config/build.d.ts(14,10):
14:10 Module '"../../../../../../../../../Users/alexanderrodriguez/Documents/git-repos/mornin.fm/node_modules/@types/webpack-hot-middleware"' has no exported.
    12 | import { BundleAnalyzerPlugin } from 'webpack-bundle-analyzer'
    13 | import { Options as WebpackDevMiddlewareOptions } from 'webpack-dev-middleware'
  > 14 | import { Options as WebpackHotMiddlewareOptions } from 'webpack-hot-middleware'
       |          ^
    15 | import { Options as HtmlMinifierOptions } from 'html-minifier'
    16 | import { Options as OptimizeCssAssetsWebpackPluginOptions } from 'optimize-css-assets-webpack-plugin'
    17 | import { TerserPluginOptions } from 'terser-webpack-plugin'

 FATAL  Nuxt build error                                                                                                                            16:45:00

  at WebpackBundler.webpackCompile (node_modules/@nuxt/webpack/dist/webpack.js:5351:21)
  at process._tickCallback (internal/process/next_tick.js:68:7)


   ╭─────────────────────────────╮
   │                             │
   │   ✖ Nuxt Fatal Error        │
   │                             │
   │   Error: Nuxt build error   │
   │                             │
   ╰─────────────────────────────╯

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mornin@1.0.0 build: `nuxt-ts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mornin@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alexanderrodriguez/.npm/_logs/2020-05-04T20_45_00_739Z-debug.log
```

**Comment by AlexR1712** [comment]
Just Happen when you use NPM, with yarn works fine
