### ISSUE TITLE
Build failed with https://vercel.com or now

### ISSUE THREAD

**Issue by subhendukundu** [fox-one/mornin.fm#9]
I just quickly tried to deploy it to vercel domain using their build system. It failed.
I tried on my local to run it with 10.15.3, it is working.
Any idea how to deploy it to now or vercel?

**Comment by lyricat** [comment]
can you provide some build logs?

**Comment by subhendukundu** [comment]
I am copy-pasting the error below.
```
$ nuxt-ts build
00:52:01.920  
 ERROR  Invalid or unexpected token
00:52:01.920  
  (function (exports, require, module, __filename, __dirname) { #!/usr/bin/env node
00:52:01.920  
  ^
00:52:01.920  
  
00:52:01.921  
  SyntaxError: Invalid or unexpected token
00:52:01.921  
  at new Script (vm.js:88:7)
00:52:01.921  
  at createScript (vm.js:263:10)
00:52:01.921  
  at Object.runInThisContext (vm.js:311:10)
00:52:01.921  
  at wrapSafe (internal/modules/cjs/loader.js:1057:15)
00:52:01.921  
  at Module._compile (internal/modules/cjs/loader.js:1120:27)
00:52:01.921  
  at Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
00:52:01.921  
  at Object.require.extensions.<computed> [as .js] (node_modules/ts-node/src/index.ts:529:44)
00:52:01.921  
  at Module.load (internal/modules/cjs/loader.js:1000:32)
00:52:01.921  
  at Function.Module._load (internal/modules/cjs/loader.js:899:14)
00:52:01.921  
  at Module.require (internal/modules/cjs/loader.js:1042:19)
00:52:01.944  
error Command failed with exit code 1.
00:52:01.944  
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
00:52:01.954  
Error: Command "yarn run build" exited with 1
00:52:04.547  
Done with "package.json"
```

**Comment by subhendukundu** [comment]
I have tried on my local with node version `v14.1.0` it throws the same error. But works when I switch the node version to `v10.15.3`.

**Comment by TgJump** [comment]
Node version 12.16.1 doesn't work either, just drop it to 10.15.3

**Comment by etewiah** [comment]
Encountered this same issue.  Would love some pointer on how to fix this so I can run with the latest version of Node.
